## Check HDF5 File
Utility notebook used to open an HDF5 ntuple and check out its contents.

In [1]:
from fill_utils import open_ntuple

In [3]:
f = "/ceph/submit/data/group/cms/store/user/lavezzo/SUEP/WH_12_8_MC_2017/QCD_Pt_600to800_TuneCP5_13TeV_pythia8+RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1+MINIAODSIM/19939C5C-D0CA-6944-9AC7-00E606F4432B.hdf5"
ntuple = open_ntuple(f)

In [ ]:
print("Found ntuple with", len(ntuple), "items. Here they are:")
print(ntuple)

Found ntuple with 3 items. Here they are:
(   genweight     event  run  luminosityBlock  PV_npvs  PV_npvsGood  \
0        1.0  25925662    1            25926       23           22
1        1.0  28801106    1            28802       19           17
3        1.0  28468089    1            28469       36           31
4        1.0  28614043    1            28615       23           19
5        1.0  28615173    1            28616       16           14

   ngood_ak4jets      ht_JEC  n_ak4jets         ht  ...  \
0              3  249.525574          3  249.12500  ...
1              3  266.434540          3  273.12500  ...
3              1  102.636993          1  101.18750  ...
4              4  382.191559          4  380.90625  ...
5              1  179.333099          1  181.25000  ...

   otherAK15_maxConst_nconst_HighestPT  otherAK15_maxPT_pt_HighestPT  \
0                                  0.0                      0.000000
1                                  0.0                      0.000000
3                                  0.0                      0.000000
4                                 29.0                    127.187208
5                                  0.0                      0.000000

   otherAK15_maxPT_eta_HighestPT otherAK15_maxPT_phi_HighestPT  \
0                       0.000000                      0.000000
1                       0.000000                      0.000000
3                       0.000000                      0.000000
4                      -1.035379                     -2.826735
5                       0.000000                      0.000000

  VH_system_mass_HighestPT VH_system_pt_HighestPT VH_system_phi_HighestPT  \
0               486.012373              95.209459               -2.205985
1               294.185405              82.306409               -2.706905
3               204.239018             154.933287               -2.094930
4               219.614191             187.399402                0.488355
5               319.378912              20.366343                2.598595

   VH_system_PuppiMET_mass_HighestPT  VH_system_PuppiMET_pt_HighestPT  \
0                         486.012373                        95.209459
1                         294.185405                        82.306409
3                         204.239018                       154.933287
4                         219.614191                       187.399402
5                         319.378912                        20.366343

   VH_system_PuppiMET_phi_HighestPT
0                         -2.205985
1                         -2.706905
3                         -2.094930
4                          0.488355
5                          2.598595

[5 rows x 180 columns], {'era': '2018', 'mc': 1, 'sample': 'X', 'gensumweight_nominal': 84000.0, 'cutflow_total_nominal': 84000.0, 'cutflow_goldenJSON_nominal': 84000.0, 'cutflow_genCuts_nominal': 84000.0, 'cutflow_triggerSingleMuon_nominal': 274.0, 'cutflow_triggerDoubleMuon_nominal': 0, 'cutflow_triggerEGamma_nominal': 590.0, 'cutflow_allTriggers_nominal': 863.0, 'cutflow_orthogonality_nominal': 17.0, 'cutflow_oneTightLepton_nominal': 8.0, 'cutflow_oneLooseLepton_nominal': 0, 'cutflow_onePhoton_nominal': 0, 'cutflow_doublePhotons_nominal': 0, 'cutflow_qualityFilters_nominal': 862.0, 'cutflow_jetHEMcut_nominal': 0, 'cutflow_electronHEMcut_nominal': 0, 'cutflow_METHEMcut_nominal': 0, 'cutflow_JetVetoMap_nominal': 0, 'cutflow_MET20_nominal': 6.0, 'cutflow_oneAK4jet_nominal': 8.0, 'cutflow_oneCluster_nominal': 5.0, 'cutflow_twoTracksInCluster_nominal': 5.0, 'gensumweight_MuScaleUp': 84000.0, 'cutflow_total_MuScaleUp': 84000.0, 'cutflow_goldenJSON_MuScaleUp': 84000.0, 'cutflow_genCuts_MuScaleUp': 84000.0, 'cutflow_triggerSingleMuon_MuScaleUp': 274.0, 'cutflow_triggerDoubleMuon_MuScaleUp': 0, 'cutflow_triggerEGamma_MuScaleUp': 590.0, 'cutflow_allTriggers_MuScaleUp': 863.0, 'cutflow_orthogonality_MuScaleUp': 17.0, 'cutflow_oneTightLepton_MuScaleUp': 8.0, 'cutflow_oneLooseLepton_MuScaleUp': 0, 'cutflow_onePhoton_MuScaleUp': 0, 'cutflow_doublePhotons_MuScaleUp': 0, 'cutflow_qualityFilters_MuScaleUp': 862.0, 'cutflow_jetHEMcut_MuScaleUp': 0, 'cutflow_electronHEMcut_MuScaleUp': 0, 'cutflow_METHEMcut_MuScaleUp': 0, 'cutflow_JetVetoMap_MuScaleUp': 0, 'cutflow_MET20_MuScaleUp': 6.0, 'cutflow_oneAK4jet_MuScaleUp': 8.0, 'cutflow_oneCluster_MuScaleUp': 5.0, 'cutflow_twoTracksInCluster_MuScaleUp': 5.0, 'gensumweight_MuScaleDown': 84000.0, 'cutflow_total_MuScaleDown': 84000.0, 'cutflow_goldenJSON_MuScaleDown': 84000.0, 'cutflow_genCuts_MuScaleDown': 84000.0, 'cutflow_triggerSingleMuon_MuScaleDown': 274.0, 'cutflow_triggerDoubleMuon_MuScaleDown': 0, 'cutflow_triggerEGamma_MuScaleDown': 590.0, 'cutflow_allTriggers_MuScaleDown': 863.0, 'cutflow_orthogonality_MuScaleDown': 17.0, 'cutflow_oneTightLepton_MuScaleDown': 8.0, 'cutflow_oneLooseLepton_MuScaleDown': 0, 'cutflow_onePhoton_MuScaleDown': 0, 'cutflow_doublePhotons_MuScaleDown': 0, 'cutflow_qualityFilters_MuScaleDown': 862.0, 'cutflow_jetHEMcut_MuScaleDown': 0, 'cutflow_electronHEMcut_MuScaleDown': 0, 'cutflow_METHEMcut_MuScaleDown': 0, 'cutflow_JetVetoMap_MuScaleDown': 0, 'cutflow_MET20_MuScaleDown': 6.0, 'cutflow_oneAK4jet_MuScaleDown': 8.0, 'cutflow_oneCluster_MuScaleDown': 5.0, 'cutflow_twoTracksInCluster_MuScaleDown': 5.0, 'gensumweight_track_down': 84000.0, 'cutflow_total_track_down': 84000.0, 'cutflow_goldenJSON_track_down': 84000.0, 'cutflow_genCuts_track_down': 84000.0, 'cutflow_triggerSingleMuon_track_down': 274.0, 'cutflow_triggerDoubleMuon_track_down': 0, 'cutflow_triggerEGamma_track_down': 590.0, 'cutflow_allTriggers_track_down': 863.0, 'cutflow_orthogonality_track_down': 17.0, 'cutflow_oneTightLepton_track_down': 8.0, 'cutflow_oneLooseLepton_track_down': 0, 'cutflow_onePhoton_track_down': 0, 'cutflow_doublePhotons_track_down': 0, 'cutflow_qualityFilters_track_down': 862.0, 'cutflow_jetHEMcut_track_down': 0, 'cutflow_electronHEMcut_track_down': 0, 'cutflow_METHEMcut_track_down': 0, 'cutflow_JetVetoMap_track_down': 0, 'cutflow_MET20_track_down': 6.0, 'cutflow_oneAK4jet_track_down': 8.0, 'cutflow_oneCluster_track_down': 5.0, 'cutflow_twoTracksInCluster_track_down': 5.0}, {'leading_ak15_pt': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt', label='leading_ak15_pt'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6), 'leading_ak15_pt_60gev': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt_60gev', label='leading_ak15_pt_60gev'), storage=Weight()) # Sum: WeightedSum(value=5, variance=5), 'n_ak15': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15', label='n_ak15'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6), 'n_ak15_60gev': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15_60gev', label='n_ak15_60gev'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6)})

In [4]:
df = ntuple[0]
metadata = ntuple[1]
hists = ntuple[2]

In [9]:
df

,genweight,event,run,luminosityBlock,PV_npvs,PV_npvsGood,ngood_ak4jets,ht_JEC,n_ak4jets,ht,...,otherAK15_maxConst_nconst_HighestPT,otherAK15_maxPT_pt_HighestPT,otherAK15_maxPT_eta_HighestPT,otherAK15_maxPT_phi_HighestPT,VH_system_mass_HighestPT,VH_system_pt_HighestPT,VH_system_phi_HighestPT,VH_system_PuppiMET_mass_HighestPT,VH_system_PuppiMET_pt_HighestPT,VH_system_PuppiMET_phi_HighestPT
0,1.0,26652094.0,1.0,26653.0,30.0,27.0,6.0,1678.883179,6.0,1679.50000,...,28.0,308.680858,-0.010499,-0.382496,998.958197,871.883533,2.634306,998.958197,871.883533,2.634306
0,1.0,26654909.0,1.0,26655.0,23.0,22.0,4.0,1612.268433,4.0,1610.37500,...,24.0,226.139464,1.544468,-0.644430,278.061892,258.264970,1.068039,278.061892,258.264970,1.068039
0,1.0,24051614.0,1.0,24052.0,40.0,39.0,4.0,824.364746,4.0,822.28125,...,0.0,0.000000,0.000000,0.000000,1198.305843,426.182187,-0.316381,1198.305843,426.182187,-0.316381
0,1.0,24052627.0,1.0,24053.0,23.0,21.0,2.0,1298.958374,2.0,1295.50000,...,21.0,204.418465,0.808499,0.745332,296.368408,260.314931,-2.421517,296.368408,260.314931,-2.421517
0,1.0,24053943.0,1.0,24054.0,35.0,30.0,3.0,830.932922,3.0,830.84375,...,0.0,0.000000,0.000000,0.000000,1218.876933,368.155704,-0.594393,1218.876933,368.155704,-0.594393
0,1.0,26118832.0,1.0,26119.0,39.0,37.0,3.0,906.484558,3.0,901.81250,...,0.0,0.000000,0.000000,0.000000,1111.380012,462.572505,2.202283,1111.380012,462.572505,2.202283
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1.0,43602780.0,1.0,43603.0,26.0,23.0,6.0,1279.675781,6.0,1273.71875,...,49.0,250.556095,-0.380635,-2.906852,580.407751,396.631461,0.321615,580.407751,396.631461,0.321615
0,1.0,26587232.0,1.0,26588.0,30.0,28.0,3.0,1491.767456,3.0,1497.43750,...,19.0,313.838875,-0.222947,2.626908,465.074060,378.883387,-0.591878,465.074060,378.883387,-0.591878
1,1.0,26587934.0,1.0,26588.0,34.0,31.0,2.0,1077.984131,2.0,1082.00000,...,0.0,0.000000,0.000000,0.000000,305.349319,101.686490,-2.112603,305.349319,101.686490,-2.112603

In [63]:
metadata

{'era': '2018',
 'mc': 1,
 'sample': 'X',
 'gensumweight_nominal': 84000.0,
 'cutflow_total_nominal': 84000.0,
 'cutflow_goldenJSON_nominal': 84000.0,
 'cutflow_genCuts_nominal': 84000.0,
 'cutflow_triggerSingleMuon_nominal': 274.0,
 'cutflow_triggerDoubleMuon_nominal': 0,
 'cutflow_triggerEGamma_nominal': 590.0,
 'cutflow_allTriggers_nominal': 863.0,
 'cutflow_orthogonality_nominal': 17.0,
 'cutflow_oneTightLepton_nominal': 8.0,
 'cutflow_oneLooseLepton_nominal': 0,
 'cutflow_onePhoton_nominal': 0,
 'cutflow_doublePhotons_nominal': 0,
 'cutflow_qualityFilters_nominal': 862.0,
 'cutflow_jetHEMcut_nominal': 0,
 'cutflow_electronHEMcut_nominal': 0,
 'cutflow_METHEMcut_nominal': 0,
 'cutflow_JetVetoMap_nominal': 0,
 'cutflow_MET20_nominal': 6.0,
 'cutflow_oneAK4jet_nominal': 8.0,
 'cutflow_oneCluster_nominal': 5.0,
 'cutflow_twoTracksInCluster_nominal': 5.0,
 'gensumweight_MuScaleUp': 84000.0,
 'cutflow_total_MuScaleUp': 84000.0,
 'cutflow_goldenJSON_MuScaleUp': 84000.0,
 'cutflow_genCuts_MuScaleUp': 84000.0,
 'cutflow_triggerSingleMuon_MuScaleUp': 274.0,
 'cutflow_triggerDoubleMuon_MuScaleUp': 0,
 'cutflow_triggerEGamma_MuScaleUp': 590.0,
 'cutflow_allTriggers_MuScaleUp': 863.0,
 'cutflow_orthogonality_MuScaleUp': 17.0,
 'cutflow_oneTightLepton_MuScaleUp': 8.0,
 'cutflow_oneLooseLepton_MuScaleUp': 0,
 'cutflow_onePhoton_MuScaleUp': 0,
 'cutflow_doublePhotons_MuScaleUp': 0,
 'cutflow_qualityFilters_MuScaleUp': 862.0,
 'cutflow_jetHEMcut_MuScaleUp': 0,
 'cutflow_electronHEMcut_MuScaleUp': 0,
 'cutflow_METHEMcut_MuScaleUp': 0,
 'cutflow_JetVetoMap_MuScaleUp': 0,
 'cutflow_MET20_MuScaleUp': 6.0,
 'cutflow_oneAK4jet_MuScaleUp': 8.0,
 'cutflow_oneCluster_MuScaleUp': 5.0,
 'cutflow_twoTracksInCluster_MuScaleUp': 5.0,
 'gensumweight_MuScaleDown': 84000.0,
 'cutflow_total_MuScaleDown': 84000.0,
 'cutflow_goldenJSON_MuScaleDown': 84000.0,
 'cutflow_genCuts_MuScaleDown': 84000.0,
 'cutflow_triggerSingleMuon_MuScaleDown': 274.0,
 'cutflow_triggerDoubleMuon_MuScaleDown': 0,
 'cutflow_triggerEGamma_MuScaleDown': 590.0,
 'cutflow_allTriggers_MuScaleDown': 863.0,
 'cutflow_orthogonality_MuScaleDown': 17.0,
 'cutflow_oneTightLepton_MuScaleDown': 8.0,
 'cutflow_oneLooseLepton_MuScaleDown': 0,
 'cutflow_onePhoton_MuScaleDown': 0,
 'cutflow_doublePhotons_MuScaleDown': 0,
 'cutflow_qualityFilters_MuScaleDown': 862.0,
 'cutflow_jetHEMcut_MuScaleDown': 0,
 'cutflow_electronHEMcut_MuScaleDown': 0,
 'cutflow_METHEMcut_MuScaleDown': 0,
 'cutflow_JetVetoMap_MuScaleDown': 0,
 'cutflow_MET20_MuScaleDown': 6.0,
 'cutflow_oneAK4jet_MuScaleDown': 8.0,
 'cutflow_oneCluster_MuScaleDown': 5.0,
 'cutflow_twoTracksInCluster_MuScaleDown': 5.0,
 'gensumweight_track_down': 84000.0,
 'cutflow_total_track_down': 84000.0,
 'cutflow_goldenJSON_track_down': 84000.0,
 'cutflow_genCuts_track_down': 84000.0,
 'cutflow_triggerSingleMuon_track_down': 274.0,
 'cutflow_triggerDoubleMuon_track_down': 0,
 'cutflow_triggerEGamma_track_down': 590.0,
 'cutflow_allTriggers_track_down': 863.0,
 'cutflow_orthogonality_track_down': 17.0,
 'cutflow_oneTightLepton_track_down': 8.0,
 'cutflow_oneLooseLepton_track_down': 0,
 'cutflow_onePhoton_track_down': 0,
 'cutflow_doublePhotons_track_down': 0,
 'cutflow_qualityFilters_track_down': 862.0,
 'cutflow_jetHEMcut_track_down': 0,
 'cutflow_electronHEMcut_track_down': 0,
 'cutflow_METHEMcut_track_down': 0,
 'cutflow_JetVetoMap_track_down': 0,
 'cutflow_MET20_track_down': 6.0,
 'cutflow_oneAK4jet_track_down': 8.0,
 'cutflow_oneCluster_track_down': 5.0,
 'cutflow_twoTracksInCluster_track_down': 5.0}

In [64]:
hists

{'leading_ak15_pt': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt', label='leading_ak15_pt'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6),
 'leading_ak15_pt_60gev': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt_60gev', label='leading_ak15_pt_60gev'), storage=Weight()) # Sum: WeightedSum(value=5, variance=5),
 'n_ak15': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15', label='n_ak15'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6),
 'n_ak15_60gev': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15_60gev', label='n_ak15_60gev'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6)}

In [75]:
ntuple_track_down = open_ntuple("../out.hdf5", df_name="vars_track_down", hist_name="hists_track_down")

df_track_down = ntuple_track_down[0]
metadata_track_down = ntuple_track_down[1]
hists_track_down = ntuple_track_down[2]

In [76]:
df_track_down

,genweight,event,run,luminosityBlock,PV_npvs,PV_npvsGood,ngood_ak4jets,ht_JEC,n_ak4jets,ht,...,otherAK15_maxConst_nconst_HighestPT,otherAK15_maxPT_pt_HighestPT,otherAK15_maxPT_eta_HighestPT,otherAK15_maxPT_phi_HighestPT,VH_system_mass_HighestPT,VH_system_pt_HighestPT,VH_system_phi_HighestPT,VH_system_PuppiMET_mass_HighestPT,VH_system_PuppiMET_pt_HighestPT,VH_system_PuppiMET_phi_HighestPT
0,1.0,25925662,1,25926,23,22,3,249.525574,3,249.12500,...,0.0,0.000000,0.000000,0.000000,486.012373,95.209459,-2.205985,486.012373,95.209459,-2.205985
1,1.0,28801106,1,28802,19,17,3,266.434540,3,273.12500,...,0.0,0.000000,0.000000,0.000000,294.185405,82.306409,-2.706905,294.185405,82.306409,-2.706905
3,1.0,28468089,1,28469,36,31,1,102.636993,1,101.18750,...,0.0,0.000000,0.000000,0.000000,204.239018,154.933287,-2.094930,204.239018,154.933287,-2.094930
4,1.0,28614043,1,28615,23,19,4,382.191559,4,380.90625,...,29.0,127.187208,-1.035379,-2.826735,219.614191,187.399402,0.488355,219.614191,187.399402,0.488355
5,1.0,28615173,1,28616,16,14,1,179.333099,1,181.25000,...,0.0,0.000000,0.000000,0.000000,319.378912,20.366343,2.598595,319.378912,20.366343,2.598595

In [77]:
hists_track_down

{'leading_ak15_pt': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt', label='leading_ak15_pt'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6),
 'leading_ak15_pt_60gev': Hist(Variable(array([   0.,    1.,    2., ...,  998.,  999., 1000.]), name='leading_ak15_pt_60gev', label='leading_ak15_pt_60gev'), storage=Weight()) # Sum: WeightedSum(value=5, variance=5),
 'n_ak15': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15', label='n_ak15'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6),
 'n_ak15_60gev': Hist(Variable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], name='n_ak15_60gev', label='n_ak15_60gev'), storage=Weight()) # Sum: WeightedSum(value=6, variance=6)}